export const environment = {
  production: false,
  DWOLLA_KEY: '',
  DWOLLA_SECRET: '',
  PLAID_CLIENT_ID: '',
  PLAID_SECRET: '',
  APPWRITE_ENDPOINT:"",
  APPWRITE_PROJECT:"",
  APPWRITE_KEY:"",
  APPWRITE_DATABASE_ID: '',
  APPWRITE_USER_COLLECTION_ID: '',
  APPWRITE_BANK_COLLECTION_ID: '',

};
